/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo =
{
	name ="CSGO SPlugin",
	author = "GameBrosDK",
	description = "M",
	version = "1.0",
	url = "http://Gamebros.dk"
}
 
public OnPluginStart()
{
	RegAdminCmd("sm_test", Command_Something, ADMFLAG_SLAY, "This is a test command");
}

public Action:Command_Something(client, args)
{
	if(args < 1)
	{
	PrintToConsole(client, "[SM] usage: sm_test <message>");
	return Plugin_Handled;
	}
	
	new String:Arg1[32], String:name[32];
	
	GetCmdArg(1, Arg1, sizeof(Arg1));
	GetClientName(client, name, sizeof(name));
	PrintToChatAll("%s: %s",name, Arg1);
	
	return Plugin_Handled;
}